version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app:cached
    command: ["npm", "run", "dev"]
